pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        EKS_CLUSTER = "t2s-cluster"
        ECR_REPO = "backend-nodejs"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $ECR_REPO:latest .'
            }
        }

        stage('Push to AWS ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                docker tag $ECR_REPO:latest $ECR_REPO:$BUILD_NUMBER
                docker push $ECR_REPO:$BUILD_NUMBER
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER
                kubectl set image deployment/backend-nodejs backend-nodejs=$ECR_REPO:$BUILD_NUMBER
                '''
            }
        }
    }
}