name: Deploy Node.js Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPO }}/backend-nodejs:latest .

      - name: Push to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}
          docker push ${{ secrets.AWS_ECR_REPO }}/backend-nodejs:latest

      - name: Deploy to EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name t2s-cluster
          kubectl rollout restart deployment/backend-nodejs